version: '3'
services:
  web:
    build: ./web
    ports:
     - "8000:8000"
  server:
    image: roboserver
    build: ./server
    restart: always
    ports:
      - "3011:3011"
      - "3012:3012"
        #    volumes:
        # - /server/config:/server/config
    entrypoint:
      - target/debug/rd-server
      - -v
  client:
    build: ./client
    depends_on:
      - server
    entrypoint:
      - ./roboclient.py
      - --lib_dir
      - lib
      # - --help
      - --host
      - server
      - run
